# -*- coding: utf-8 -*-
"""Q3_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWm-EWFDEwI15WbGIT0_bUIrxolF7Z1G
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
# from os import path
# import os

N=60
x = np.array([i*np.pi/180 for i in range(60,300,2)])
np.random.seed(10)
y = 3*x + 8 + np.random.normal(0,3,len(x)) 
x=x.reshape((len(x),-1))

# y=pd.Series(y)
LR = LinearRegression(fit_intercept=True)
LR.fit_gradient_descent(x, y, batch_size=40, num_iters=100, lr=0.001,gradient_type='jax')
a=LR.plot_surface(x,y,LR.all_coef.iloc[0],LR.all_coef.iloc[1])
plt.show()
b=LR.plot_line_fit(x,y,LR.coef[0],LR.coef[1],0)
plt.show()
c=LR.plot_contour(x,y,LR.all_coef.iloc[0],LR.all_coef.iloc[1])
plt.show()