# -*- coding: utf-8 -*-
"""Q4_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dUjXq9nEOX2PMOboEnFAB_-x-hQGM49x
"""

import numpy as np
import matplotlib.pyplot as plt
from preprocessing.polynomial_features import PolynomialFeatures
from linearRegression.linear_regression import LinearRegression
import pandas as pd
import os.path
from os import path
np.random.seed(45)  #Setting seed for reproducibility

# if not path.exists('Plots/Question4/'):
#   os.makedirs('Plots/Question4/')

x = np.array([i*np.pi/180 for i in range(60,300,2)])
y = 3*x + 8 + np.random.normal(0,3,len(x))
# x=x.reshape((len(x),-1))
#TODO : Write here
#Preprocess the input using the polynomial features
#Solve the resulting linear regression problem by calling any one of the 
#algorithms you have implemented.
poly=PolynomialFeatures(degree=3)
x2=poly.transform(x)
LR = LinearRegression(fit_intercept=True)
LR.fit_normal_equations(x2,y)
d=np.arange(2,20,1)
l=[]
for i in d:
    poly=PolynomialFeatures(degree=i)
    x2=poly.transform(x)
    LR = LinearRegression(fit_intercept=True)
    LR.fit_sklearn_LR(x2,y)
    l.append(np.log(np.dot(LR.coef.T,LR.coef)))
plt.plot(d,l)
plt.show()