# -*- coding: utf-8 -*-
"""Q7_forecast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QygJyzTuf4wJ3ioxCqF0boFIbPNbBJd6
"""

import numpy as np

#TODO : Write here
from linearRegression.linear_regression import LinearRegression
from pandas import read_csv
from matplotlib import pyplot

class AutoRegressor():
    def __init__(self,lag):
        # self.train=train
        self.lag=lag
        self.model=None
    def fit(self,X):
        # X=self.train
        shap=int(len(X)/(self.lag+1))
        X=X[:(shap*(self.lag+1))]
        Xtrain=np.array(X).reshape((shap,self.lag+1))
        Xt,yt=Xtrain[:,0:-1],Xtrain[:,-1]
        model=LinearRegression()
        model.fit_SVD(Xt,yt)
        self.model=model
    def predict(self,X,d):
        xpred=list(X[-self.lag:])
        y=[]
        print(len(xpred))
        # xpred.insert(0,1)
        # print((np.array(xpred)).reshape(1,30).shape)
        # print(len(xxpred.insert(0,1)))
        for i in range(d):
            
            # x1=self.model.predict(np.array(xpred).reshape(1,len(xpred)))
            
            x1=self.model.predict(xpred)
            # print(x1[0])
            y.append(x1[0])
            xpred.append(y[-1])
            xpred=xpred[-self.lag:]
            # xpred.insert(0,1)
            # print(xpred)
        return y
# series = read_csv('daily-min-temperatures.csv', header=0, index_col=0)
# print(series.head())
# series.plot()
# pyplot.show()
series = read_csv('daily-min-temperatures.csv', header=0, index_col=0, parse_dates=True, squeeze=True)
# split dataset
X = series.values
train, test = X[1:len(X)-7], X[len(X)-7:]
# train autoregression
model = AutoRegressor(lag=29)
model.fit(train)
# print('Coefficients: %s' % model_fit.params)
# make predictions
predictions = model.predict(train,7)
for i in range(len(predictions)):
 print('predicted=%f, expected=%f' % (predictions[i], test[i]))
rmse = np.sqrt((np.array(predictions)-np.array(test))**2)

# print('Test RMSE: %.3f' % rmse)
print(rmse)
# # plot results
pyplot.plot(test)
pyplot.plot(predictions, color='red')
pyplot.show()